# Generated by Django 3.0.6 on 2020-05-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='human',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
